### ISSUE TITLE
Join Professional Summit 2021 link only works from home page.

### ISSUE THREAD

**Issue by jcassidyav** [NativeScript/docs-new#27]
The link only works from the home page but not the docs page etc. where it also appears.
I wasn't sure if .vitepress\theme\nativescript-theme\index.js was the place to change it as it looks like generated code.

**Comment by rigor789** [comment]
Hey @jcassidyav thanks for the heads up - yep that file is generated from a private repository at the moment, so we'll need to fix it there first & rebuild.
