### ISSUE TITLE
Content jumps after page is loaded

### ISSUE THREAD

**Issue by janoshrubos** [NativeScript/docs-new#34]
Posted by: @vallemar https://github.com/NativeScript/NativeScript/issues/9302

When you search in the documents: for example Label, if you click on the first option it first takes you to https://docs.nativescript.org/ui-and-styling.html#label and then changes to https://docs.nativescript.org/ui-and-styling.html#frame in my case. Does the same with everything. 

It's a bit random, sometimes it leads to the section and sometimes it doesn't. (for me most do not)

**Comment by DiySane** [comment]
May I work on this issue as part of Hacktoberfest?

**Comment by DiySane** [comment]
@janoshrubos kindly assign this issue to me.

**Comment by janoshrubos** [comment]
@DiySane the source code of the docs and the theme is in a private repo, so unfortunately I couldn't assign it to you

**Comment by DiySane** [comment]
Okay, no problem @janoshrubos . Feel free to tag me for any future issue.

**Comment by janoshrubos** [comment]
@DiySane sure, will do! thank you very much!

**Comment by vallemar** [comment]
Hello @janoshrubos,

I know this is not the highest priority, but is there any progress? It is very annoying to search the documents and always take you somewhere else

**Comment by vallemar** [comment]
I do not want to be annoying 😅, but I still find these jumps incredibly annoying when doing a search

**Comment by rigor789** [comment]
Fixed in https://github.com/NativeScript/docs-new/commit/09f11c93798d0338b5f0aacff3ee1187ae3f4d2b

(we are reworking parts of the docs however, but in the meantime this should reduce the issue if not completely fix it)

**Comment by vallemar** [comment]
Awesome!

**Comment by rigor789** [comment]
Noticed a few more cases that aren't handled, but should be vastly better now - also improved our search indexing so quick search should yield more relevant results now :D
