### ISSUE TITLE
png images in tutorials

### ISSUE THREAD

**Issue by winescout** [NativeScript/docs-new#64]
In the tutorials:
https://github.com/NativeScript/docs-new/blob/develop/tutorial/plain.md?plain=1#L164
https://github.com/NativeScript/docs-new/blob/develop/tutorial/react.md?plain=1#L171
https://github.com/NativeScript/docs-new/blob/develop/tutorial/angular.md?plain=1#L222
https://github.com/NativeScript/docs-new/blob/develop/tutorial/svelte.md?plain=1#L140
https://github.com/NativeScript/docs-new/blob/develop/tutorial/vue.md?plain=1#L151

Local rareness to images are setup, but those images are not provided in the tutorial.  

I did some url hacking to try and find them, but wasn't successful.  Can we link to a directory that contains some sample images?

**Comment by rigor789** [comment]
The assets can be found in the repo linked at the start ([here](https://github.com/NativeScript/docs-new/blob/fea21e4db6697e91958f8eb7d5ddc8acc0cf5118/tutorial/plain.md?plain=1#L25))
https://github.com/NativeScript/tutorials/blob/main/plain-tutorial/app/assets/bookofmormon.png

**Comment by winescout** [comment]
Thanks rigor.  I'll open a new PR pointing this out at that point in the tutorial.

**Comment by rigor789** [comment]
Fixed in #65
