### ISSUE TITLE
Typo in image label in tutorials

### ISSUE THREAD

**Issue by dap6000** [NativeScript/docs-new#70]
See this image -> https://docs.nativescript.org/assets/images/tutorial/tutorial-example-app-details-breakdown.png

Has a label that says "Here Image" while the tutorial text refers to it as the "Hero Image".  The `assets/images/tutorial/` directory doesn't seem to exist here in the repo. I'm not sure what it would take to replace the image in production.

**Comment by rigor789** [comment]
It's here: https://github.com/NativeScript/docs-new/blob/44075a4beb95c789f4b710fd441efd9f7dc4845e/public/assets/images/tutorial/tutorial-example-app-details-breakdown.png

@williamjuan027 you might have the source file to fix it? `Here Image` -> `Hero Image`

**Comment by williamjuan027** [comment]
@rigor789 I've uploaded an updated image in https://github.com/NativeScript/docs-new/issues/70
